Algoritmo "ENQUANTO"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 8/11/2025
Var
// Seção de Declarações das variáveis 
  n:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("escreva um numero:")
   leia(n)
   enquanto (n<10)faca
      escreval("Numero invalido")
      escreva("infome um  numero:")
      leia(n)
   fimenquanto

Fimalgoritmo