Algoritmo "TABUADA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 8/12/2025
Var
// Seção de Declarações das variáveis 
  CONT,N,r:REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  CONT<-1
  ESCREVA("ESCREVA UM NUMERO:")
  LEIA(N)
  ENQUANTO (CONT<=10)FACA
      r<-cont*n
      ESCREVA(r)
      CONT<-CONT+1
  FIMENQUANTO

Fimalgoritmo