Algoritmo "TESTEENQUANTO"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 8/11/2025
Var
   // Seção de Declarações das variáveis
   n1,n2,s:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   repita
      escreva("digite um numero: ")
      leia(n1)
      escreva("digite um numero: ")
      leia(n2)
       s<-n1+n2
       escreva(s)
   ate(s>=100)
   escreva("O resultado e",s)
Fimalgoritmo