Algoritmo "TESTECHATGPT"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 8/12/2025
Var
   // Seção de Declarações das variáveis
   r,n:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   r<-0
   escreva("digite um numero:")
   leia(n)
   enquanto (n<>0)faca
       r<-r+n
      escreva ("escreva outro numero:")
      leia(n)
   fimenquanto
   escreva("o resultado dos numeros digitados foi ",r)

Fimalgoritmo