Algoritmo "contadorinteligente"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 8/10/2025
Var
   // Seção de Declarações das variáveis
   contador,constante,n:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contador<-10
   constante<-0
   repita
      escreval("escreva um numero:")
      leia(n)
      se(n=1) entao
         enquanto (constante<=10)faca
            escreva(constante)
            constante<-constante+1
         fimenquanto
      fimse
      se(n=2)entao
         enquanto (contador>=0)faca
            escreva(contador)
            contador<-contador-1
         fimenquanto
         se(n=3)entao
         fimse
      fimse
   ate(n=3)




Fimalgoritmo
