Algoritmo "erro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 8/12/2025
Var
// Seção de Declarações das variáveis 
n,s:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  s<-0
  escreva("escreva um numero:")
  leia(n)
  enquanto (n>=0)faca
      escreva("digite outro numero(ou negativo para parar):")
      leia(n)
      s<-s+n
  fimenquanto
  escreva("a soma e ",s)
Fimalgoritmo